### ISSUE TITLE
JNI编译问题

### ISSUE THREAD

**Issue by pingor** [xl-player-developers/xl_player#1]
目前的工程中，JNI是个麻烦事。
JNI为啥不使用android.mk编译呢

**Comment by gutou121** [comment]
您好，谢谢关注。
现在Android Studio使用cmke编译jni部分，具体脚本参考项目中的CMakeList.txt。
推荐使用Android Studio开发。
如果不使用IDE，可以自已安装gradle。gradle会自动配置cmake完成编译，具体使用方法参考gradle官方网站。
